export const state = {
  tab: "dashboard",
  sbTab: "projects",
  ai: "anthropic",
  aiModel: "claude-sonnet-4-6",
  userName: "",
  userRole: "",
  waveFrozen: false,
  busy: false,
  streamBubbles: {},
  currentGateId: null,
  gateOpen: false,
  enfOpen: false,
  keyVisible: false,
  updateChannel: "beta",
  workspace: "",
  termHistory: [],
  termHistIdx: -1,
};
