# Concept adapted from a5c-ai/babysitter (MIT). No source code copied.
# cli/signalos_lib/commands/plan.py
# W3.4 — signalos plan subcommand (AMD-CORE-017)

from __future__ import annotations

__all__ = ["main"]

import json
import sys
from pathlib import Path


def main(argv: list[str]) -> int:
    import argparse

    parser = argparse.ArgumentParser(
        prog="signalos plan",
        description=(
            "Machine-readable task schema commands (W3.4, AMD-CORE-017).\n\n"
            "PLAN.tasks.yaml is the authoritative task list. PLAN.md is a\n"
            "rendered view generated by `signalos plan render`.\n\n"
            "Actions:\n"
            "  render    Generate PLAN.md from PLAN.tasks.yaml\n"
            "  validate  Check PLAN.tasks.yaml against the schema\n"
            "  list      Print tasks (optionally filtered by status)\n"
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "action",
        choices=["render", "validate", "list"],
        help="Subcommand to run.",
    )
    parser.add_argument(
        "--input",
        default=None,
        metavar="PATH",
        help="Path to PLAN.tasks.yaml (default: PLAN.tasks.yaml in cwd).",
    )
    parser.add_argument(
        "--output",
        default=None,
        metavar="PATH",
        help="render: output path for PLAN.md (default: PLAN.md in cwd).",
    )
    parser.add_argument(
        "--status",
        default=None,
        metavar="STATUS",
        help="list: filter to tasks with this status.",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        dest="as_json",
        help="list/validate: emit JSON instead of human-readable output.",
    )

    args = parser.parse_args(argv)
    action = args.action

    # Resolve input path
    input_path = Path(args.input) if args.input else Path.cwd() / "PLAN.tasks.yaml"

    # ── render ────────────────────────────────────────────────────────────
    if action == "render":
        return _cmd_render(input_path, args)

    # ── validate ─────────────────────────────────────────────────────────
    if action == "validate":
        return _cmd_validate(input_path, args)

    # ── list ─────────────────────────────────────────────────────────────
    if action == "list":
        return _cmd_list(input_path, args)

    parser.print_help(sys.stderr)
    return 1


# ---------------------------------------------------------------------------
# Subcommand implementations
# ---------------------------------------------------------------------------

def _load(path: Path):
    """Load a plan doc, writing a user-friendly error on failure."""
    from signalos_lib.plan import load_tasks
    try:
        return load_tasks(path)
    except FileNotFoundError as exc:
        sys.stderr.write(f"signalos plan: {exc}\n")
        return None
    except Exception as exc:  # noqa: BLE001
        sys.stderr.write(f"signalos plan: failed to parse {path}: {exc}\n")
        return None


def _cmd_render(input_path: Path, args) -> int:
    from signalos_lib.plan import render_plan_md, validate_tasks

    doc = _load(input_path)
    if doc is None:
        return 2

    # Validate before rendering — warn but don't block
    errors = validate_tasks(doc)
    if errors:
        sys.stderr.write("signalos plan render: validation warnings:\n")
        for e in errors:
            sys.stderr.write(f"  • {e}\n")

    md = render_plan_md(doc)

    output_path = Path(args.output) if args.output else input_path.parent / "PLAN.md"
    try:
        output_path.write_text(md, encoding="utf-8")
    except OSError as exc:
        sys.stderr.write(f"signalos plan render: cannot write {output_path}: {exc}\n")
        return 2

    sys.stdout.write(f"signalos plan render: wrote {output_path} ({len(doc.tasks)} tasks)\n")
    return 0


def _cmd_validate(input_path: Path, args) -> int:
    from signalos_lib.plan import validate_tasks

    doc = _load(input_path)
    if doc is None:
        return 2

    errors = validate_tasks(doc)

    if args.as_json:
        sys.stdout.write(
            json.dumps({"valid": len(errors) == 0, "errors": errors}, ensure_ascii=False) + "\n"
        )
        return 0 if not errors else 1

    if not errors:
        sys.stdout.write(f"signalos plan validate: OK ({len(doc.tasks)} tasks, 0 errors)\n")
        return 0

    sys.stderr.write(f"signalos plan validate: FAIL — {len(errors)} error(s)\n")
    for e in errors:
        sys.stderr.write(f"  • {e}\n")
    return 1


def _cmd_list(input_path: Path, args) -> int:
    from signalos_lib.plan import VALID_STATUSES, _STATUS_ICON  # type: ignore[attr-defined]

    doc = _load(input_path)
    if doc is None:
        return 2

    tasks = doc.tasks

    # Filter by status
    if args.status:
        if args.status not in VALID_STATUSES:
            sys.stderr.write(
                f"signalos plan list: unknown status {args.status!r} "
                f"(valid: {sorted(VALID_STATUSES)})\n"
            )
            return 2
        tasks = [t for t in tasks if t.status == args.status]

    if args.as_json:
        sys.stdout.write(
            json.dumps(
                {
                    "wave": doc.wave,
                    "tasks": [t.to_dict() for t in tasks],
                    "count": len(tasks),
                },
                ensure_ascii=False,
            )
            + "\n"
        )
        return 0

    # Human-readable table
    if not tasks:
        sys.stdout.write("(no tasks)\n")
        return 0

    _print_table(tasks)
    return 0


def _print_table(tasks) -> None:
    from signalos_lib.plan import _STATUS_ICON  # type: ignore[attr-defined]

    # Dynamic column widths
    title_w = max(len(t.title) for t in tasks)
    title_w = max(title_w, 5)

    header = f"  {'#':<4}  {'St':<12}  {'Ti':<3}  {'Eff':>4}  {'Title':<{title_w}}  Owner"
    sep = "  " + "-" * (len(header) - 2)
    sys.stdout.write(header + "\n")
    sys.stdout.write(sep + "\n")

    for i, task in enumerate(tasks, 1):
        icon = _STATUS_ICON.get(task.status, "?")
        status_str = f"{icon} {task.status}"
        effort_str = f"{task.effort_days:g}d"
        owner = task.owner or "—"
        sys.stdout.write(
            f"  {i:<4}  {status_str:<12}  {task.tier:<3}  {effort_str:>4}  {task.title:<{title_w}}  {owner}\n"
        )
