"""Generate an interactive HTML prototype of the product design.

The preview is a REAL interactive prototype generated by an LLM agent.
The user can click through navigation, see forms respond, see tables
sort. SignalOS does NOT hardcode HTML templates -- that's the agent's
job.

If no API key is configured, the function returns a minimal page
explaining that a provider key is needed for the design preview.
"""

from __future__ import annotations

__all__ = ["generate_design_preview_html"]

import json
import os
from typing import Any
from .llm_provider import is_llm_available


def generate_design_preview_html(design: dict, intent: dict) -> str:
    """Generate an interactive HTML prototype for design approval.

    Dispatches to the LLM to produce a full interactive single-page
    HTML app (clickable nav, working forms, sortable tables, responsive
    layout) using the selected design system.

    If no API key is available, returns a page explaining the requirement.
    SignalOS does not fake what agents should produce.
    """
    if is_llm_available():
        result = _generate_with_llm(design, intent)
        if result:
            return result

    # No API key or LLM call failed -- return honest "needs key" page
    return _no_api_key_page(design, intent)


def _generate_with_llm(design: dict, intent: dict) -> str | None:
    """Use LLM to generate a full interactive HTML prototype."""
    try:
        from signalos_lib.harness import _resolve_provider, resolve_model
    except ImportError:
        return None

    ui_lib = design.get("ui_library", {})
    ui_name = ui_lib.get("name", "shadcn/ui") if isinstance(ui_lib, dict) else str(ui_lib)
    tokens = design.get("design_tokens", {})
    primary_color = tokens.get("primary_color", "#3b82f6")
    font = tokens.get("font_family", "Inter, sans-serif")
    entities = intent.get("entities", [])
    product_name = intent.get("product_name", "Product")
    workflows = intent.get("primary_workflows", [])
    surfaces = intent.get("ux_surfaces", [])

    prompt = f"""Generate a single self-contained HTML file that is a fully interactive
prototype of a product called "{product_name}".

Design system:
- UI library style: {ui_name}
- Primary color: {primary_color}
- Font: {font}
- Entities: {json.dumps(entities)}
- Workflows: {json.dumps(workflows)}
- UX surfaces: {json.dumps(surfaces)}

Requirements:
- Self-contained single HTML file (use CDN for Tailwind/styles)
- Fully interactive: clickable navigation between pages/views
- Working forms with validation feedback (client-side)
- Sortable/filterable tables with sample data
- Responsive layout (works on mobile and desktop)
- Sidebar navigation listing all entities
- Each entity has a list view and a detail/form view
- Use realistic sample data (5-10 rows per entity)
- No placeholder text like "Lorem ipsum" -- use domain-realistic content
- Apply the primary color and font throughout
- Professional, production-quality appearance

Return ONLY the HTML. No explanation, no markdown fences, just the raw HTML starting with <!DOCTYPE html>."""

    try:
        provider = _resolve_provider()
        # No hardcoded default: SIGNALOS_LLM_MODEL → discovery from provider.
        response_text, _, _ = provider.call(prompt, resolve_model(None))
    except Exception:
        return None

    # Extract HTML from response (handle markdown fences if present)
    text = response_text.strip()
    if text.startswith("```"):
        text = text.split("\n", 1)[-1].rsplit("```", 1)[0].strip()

    # Validate it's actual HTML
    if not text.startswith("<!") and not text.startswith("<html"):
        return None

    return text


def _no_api_key_page(design: dict, intent: dict) -> str:
    """Return a page explaining that design preview requires an API key."""
    ui_lib = design.get("ui_library", {})
    ui_name = ui_lib.get("name", "") if isinstance(ui_lib, dict) else str(ui_lib)
    tokens = design.get("design_tokens", {})
    primary_color = tokens.get("primary_color", "#3b82f6")
    font = tokens.get("font_family", "Inter, sans-serif")
    product_name = intent.get("product_name", "Product")
    entities = intent.get("entities", [])

    entity_list = "".join(f"<li>{e}</li>" for e in entities) if entities else "<li>No entities extracted yet</li>"

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>{product_name} - Design Preview</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    font-family: {font};
    background: #f8f9fa;
    color: #1a1a1a;
    display: grid;
    place-items: center;
    min-height: 100vh;
    padding: 2rem;
  }}
  .card {{
    background: white;
    border-radius: 12px;
    padding: 3rem;
    max-width: 600px;
    box-shadow: 0 4px 20px rgba(0,0,0,0.08);
    text-align: center;
  }}
  h1 {{ font-size: 1.5rem; margin-bottom: 1rem; color: {primary_color}; }}
  p {{ color: #555; line-height: 1.6; margin-bottom: 1.5rem; }}
  .entities {{ text-align: left; margin: 1.5rem 0; }}
  .entities h3 {{ font-size: 0.875rem; text-transform: uppercase; letter-spacing: 0.05em; color: #888; margin-bottom: 0.5rem; }}
  .entities ul {{ list-style: none; }}
  .entities li {{ padding: 0.5rem 0; border-bottom: 1px solid #eee; }}
  .color-strip {{
    width: 100%;
    height: 8px;
    border-radius: 4px;
    background: {primary_color};
    margin: 1.5rem 0;
  }}
  .hint {{
    font-size: 0.8rem;
    color: #999;
    margin-top: 1.5rem;
    padding: 1rem;
    background: #f0f0f0;
    border-radius: 8px;
  }}
</style>
</head>
<body>
<div class="card">
  <h1>{product_name}</h1>
  <div class="color-strip"></div>
  <p>Connect an AI provider to see a full interactive prototype of your product with clickable navigation, working forms, and realistic sample data.</p>
  <div class="entities">
    <h3>Your product includes</h3>
    <ul>{entity_list}</ul>
  </div>
  <div class="hint">
    Add an AI provider key in the Vault to enable the interactive design preview.
  </div>
</div>
</body>
</html>"""
